### ISSUE TITLE
Monitoring server refuses to start

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/monitoring#5]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/monitoring/monitoring/monitoring/app.py", line 29, in <module>
    main()
  File "/home/monitoring/monitoring/monitoring/app.py", line 25, in main
    start(args.conf, args)
  File "/home/monitoring/monitoring/monitoring/app.py", line 14, in start
    app = Application(config=config, args=args, root=PKGDIR)
  File "monitoring/core/application.py", line 30, in __init__
    self.pre_init(self.config['stack.pre_init'])
  File "monitoring/core/application.py", line 50, in pre_init
    hook = self._import(hook)
  File "monitoring/core/application.py", line 102, in _import
    mod = importlib.import_module(mod)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "monitoring/ext/geoip.py", line 1, in <module>
    import GeoIP
ImportError: /home/monitoring/.virtualenvs/monitoring/local/lib/python2.7/site-packages/GeoIP.so: undefined symbol: GeoIP_teredo
```

**Comment by afaikafk** [comment]
We've rebuilt the box because it was an issue with an underlying dependency that could not be resolved easily
